name: 'Pypi'
description: 'A GitHub Action to easily bump version files'
author: 'Tommaso De Rossi'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs: 
  setup_file:
    default: ./setup.py
  username:
    required: true
  password:
    required: true
  # distributions:
  #   - sdist
  #   - bdist_wheel
env:
  PLUGIN_SETUPFILE: ${{ inputs.setup_file }}
  PLUGIN_USERNAME: ${{ inputs.username }}
  PLUGIN_PASSWORD: ${{ inputs.password }}
  # PLUGIN_DISTRIBUTIONS:
runs:
  using: 'docker'
  image: 'Dockerfile'

